name: history
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.3.1
  shared_preferences: ^2.5.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^8.2.2
  icons_launcher: ^3.0.3
  supabase_flutter: ^2.12.0
  google_fonts: ^7.0.0
  flutter_bloc: ^9.1.1
  another_flushbar: ^1.12.32

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
